#!/bin/bash

flansible_prod_dir="/usr/local/lib/python2.7/dist-packages/Flansible"
flansible_dev_dir="/home/flansible/Flansible"

/usr/sbin/sshd -D &

if [[ -z "${flansible_prod_dir}" ]]
  then
    ansible-playbook ${flansible_install_dir}/playbook/site.yml -vvv > /var/log/flansible-setup.log 2>&1
  else
    ansible-playbook ${flansible_dev_dir}/playbook/site.yml -vvv > /var/log/flansible-setup.log 2>&1
fi

cd /home/flansible/Flansible
C_FORCE_ROOT=1 celery worker -A flansible.celery --loglevel=info > /var/log/celery.log 2>&1 &
flower --broker=redis://localhost:6379/0 > /var/log/flower.log 2>&1 &
python runserver.py > /var/log/flansible.log 2>&1

