#!/bin/bash

/usr/sbin/sshd -D &

site_yml=$(flansible)
flansible_home="/home/flansible/"

if [[ "${site_yml}" ]]
  then
    ansible-playbook site_yml -vvv &> /var/log/flansible-setup.log
  else
    ansible-playbook ${flansible_home}/Flansible/playbook/site.yml -vvv &> /var/log/flansible-setup.log
fi

cd /home/flansible/Flansible
C_FORCE_ROOT=1 celery worker -A flansible.celery --loglevel=info &> ${flansible_home}/celery.log &
flower --broker=redis://localhost:6379/0 &> ${flansible_home}/flower.log &
python runserver.py &> ${flansible_home}/flansible.log &
tail -f /var/log/flansible.log
