#!/bin/bash

ansible-playbook /usr/local/lib/python2.7/dist-packages/Flansible/playbook/site.yml
/usr/sbin/sshd -D
cd /home/flansible/Flansible
C_FORCE_ROOT=1 celery worker -A flansible.celery --loglevel=info > /var/log/celery.log 2>&1 &
flower --broker=redis://localhost:6379/0 > /var/log/flower.log 2>&1 &
python runserver.py > /var/log/flansible.log 2>&1 &

/bin/bash

